# DISPLAYING PROGRAM TITLE
print ("*** PROGRAMA QUE INFORMA PRECIO DE DULCE Y CALCULA EL CAMBIO ")

# PROMTING THE USER
Cash = int(input("EL DULCE TIENE UN PRECIO DE 2000 $COP.\n¿QUÉ MONEDA VAS A USAR PARA PAGAR?: \n1. 5000 $COP.\n2. 10000 $COP.\n"))

# CHECKING THE RESPONSE AND HANDING THE CHANGE
if Cash == 1:
    print("El cambio es 3000$COP.")

else:
    print("El cambio es 8000$COP.")