# DISPLAY PROGRAM TITLE
print ("*** PROGRAMA QUE CALCULA EL ÁREA DE UN RECTÁNGULO ***")

# PROMPT THE USER THE WIDTH AND LENGTH
Ancho = int(input("INGRESAR ANCHO DEL RECTÁNGULO: "))
Largo = int(input("INGRESAR LARGO DEL RECTÁNGULO: "))

# CHECKING THAT WIDTH AND LENGTH ARE GREATER THAN CERO.
if Ancho < 0 and Largo < 0:
# PROMPTING THE USER TO ENTER A VALID VALUE
  print("FAVOR INGRESAR VALORES VÁLIDOS (>0)")
else:
# DISPLAYING THE AREA AS PER ENTERED DATA
  print(f"EL ÁREA DEL RECTANGULO DE ANCHO {Ancho} Y LARGO {Largo} ES: ",Largo*Ancho,".")