# DISPLAY PROGRAM TITLE
print ("*** PROGRAMA QUE GENERA ALARMA DE ACUERDO AL VALOR DE LA TEMPERATURA MEDIDA ***")

# PROMPT THE USER THE TEMPERATURE AND PRESSURE MEASUREMENT
Press = int(input("INGRESAR EL VALOR DE LA PRESIÓN: "))
Temp = int(input("INGRESAR ANCHO DE LA TEMPERATURA: "))


# CHECKING THE TEMPERATURE AND PRESSURE
if Press > 200 and Temp > 100:
  # GO OFF THE ALARM
  print("ALARMA!!!\nLA PRESIÓN ES SUPERIOR A 200 Y LA TEMPERATURA MAYOR A 100.")
elif Press > 200:
  # GO OFF THE ALARM
  print("ALARMA!!!\nLA PRESIÓN ES SUPERIOR A 200.")
elif Temp > 100:
  # GO OFF THE ALARM
  print("ALARMA!!!\nLA TEMPERATURA ES SUPERIOR A 100.")
else:
  # INFORM THAT EVERYTHING IS WITHIN NORMAL RANGES
  print("LAS TEMPERATURAS ESTAN DENTRO DEL RANGO NORMAL")