# DISPLAY PROGRAM TITLE
print ("*** PROGRAMA QUE CALCULA NÓMINA DE UNA EMPRESA ***")
# PROMPT THE USER CONTRACT TYPE AND WORKED HOURS

Contr = 0
while Contr != 1 and Contr != 2: 
  
  Contr = int(input("QUÉ TIPO DE CONTRATO TIENE EL COLABORADOR:\n1. PLANTA.\n2. ADMINISTRATIVO.\n"))

Hours = int(input("INGRESAR CANTIDAD DE HORAS TRABAJADOS: "))

# CHECKING THE CONTRACT TYPE
if Contr == 1:
  # DISPLAY SALARY
  print("EL SALARIO DEVENGADO ES ",Hours * 20000,"$COP.")
elif Contr == 2:
  # DISPLAY SALARY
  print("EL SALARIO DEVENGADO ES ",Hours * 10000,"$COP.")