# DISPLAY PROGRAM TITLE
print ("*** PROGRAMA QUE CALCULA NÓMINA DE UNA EMPRESA ***")
# PROMPT THE USER CONTRACT TYPE AND WORKED HOURS

C = 0
while C != 1 and C != 2: 
  
  C = int(input("QUÉ TIPO DE CONTRATO TIENE EL COLABORADOR:\n1. PLANTA.\n2. ADMINISTRATIVO.\n"))

Hours = int(input("INGRESAR CANTIDAD DE HORAS TRABAJADOS: "))

# CHECKING THE CONTRACT TYPE
if C == 1:
  # DISPLAY SALARY
  print("EL SALARIO DEVENGADO ES ",Hours * 20000,"$COP.")
elif C == 2:
  # DISPLAY SALARY
  print("EL SALARIO DEVENGADO ES ",Hours * 10000,"$COP.")